name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Master Node
        - Coordination Node
        - Data Node
        - REST API
        - Query Parser
        - Raft Consensus
        - Shard Allocation
        - CLI Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (important for my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would benefit you or others
      placeholder: |
        This feature would help me...
        It would benefit others by...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work (API examples, CLI commands, etc.)
      render: shell
      placeholder: |
        # Example usage
        curl -X POST http://localhost:9200/my-index/_search ...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this is an API feature, provide a proposed API design
      render: yaml
      placeholder: |
        # Proposed API endpoint
        POST /_new_feature
        {
          "param1": "value1"
        }

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility
      description: Check all that apply
      options:
        - label: This is a breaking change
        - label: This requires API changes
        - label: This is OpenSearch compatible
        - label: This requires documentation updates

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        Related discussions:
        Similar features in other systems:

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I am willing to help implement this feature (if applicable)
          required: false
