// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/common/proto/data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardInfo_ShardState int32

const (
	ShardInfo_SHARD_STATE_UNKNOWN      ShardInfo_ShardState = 0
	ShardInfo_SHARD_STATE_INITIALIZING ShardInfo_ShardState = 1
	ShardInfo_SHARD_STATE_STARTED      ShardInfo_ShardState = 2
	ShardInfo_SHARD_STATE_RELOCATING   ShardInfo_ShardState = 3
	ShardInfo_SHARD_STATE_CLOSED       ShardInfo_ShardState = 4
)

// Enum value maps for ShardInfo_ShardState.
var (
	ShardInfo_ShardState_name = map[int32]string{
		0: "SHARD_STATE_UNKNOWN",
		1: "SHARD_STATE_INITIALIZING",
		2: "SHARD_STATE_STARTED",
		3: "SHARD_STATE_RELOCATING",
		4: "SHARD_STATE_CLOSED",
	}
	ShardInfo_ShardState_value = map[string]int32{
		"SHARD_STATE_UNKNOWN":      0,
		"SHARD_STATE_INITIALIZING": 1,
		"SHARD_STATE_STARTED":      2,
		"SHARD_STATE_RELOCATING":   3,
		"SHARD_STATE_CLOSED":       4,
	}
)

func (x ShardInfo_ShardState) Enum() *ShardInfo_ShardState {
	p := new(ShardInfo_ShardState)
	*p = x
	return p
}

func (x ShardInfo_ShardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardInfo_ShardState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_proto_data_proto_enumTypes[0].Descriptor()
}

func (ShardInfo_ShardState) Type() protoreflect.EnumType {
	return &file_pkg_common_proto_data_proto_enumTypes[0]
}

func (x ShardInfo_ShardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardInfo_ShardState.Descriptor instead.
func (ShardInfo_ShardState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{5, 0}
}

type CreateShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShardRequest) Reset() {
	*x = CreateShardRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardRequest) ProtoMessage() {}

func (x *CreateShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardRequest.ProtoReflect.Descriptor instead.
func (*CreateShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShardRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *CreateShardRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CreateShardRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateShardRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ShardKey      string                 `protobuf:"bytes,2,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShardResponse) Reset() {
	*x = CreateShardResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardResponse) ProtoMessage() {}

func (x *CreateShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardResponse.ProtoReflect.Descriptor instead.
func (*CreateShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShardResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *CreateShardResponse) GetShardKey() string {
	if x != nil {
		return x.ShardKey
	}
	return ""
}

type DeleteShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardRequest) Reset() {
	*x = DeleteShardRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardRequest) ProtoMessage() {}

func (x *DeleteShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardRequest.ProtoReflect.Descriptor instead.
func (*DeleteShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShardRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *DeleteShardRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type DeleteShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardResponse) Reset() {
	*x = DeleteShardResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardResponse) ProtoMessage() {}

func (x *DeleteShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardResponse.ProtoReflect.Descriptor instead.
func (*DeleteShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShardResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type GetShardInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardInfoRequest) Reset() {
	*x = GetShardInfoRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardInfoRequest) ProtoMessage() {}

func (x *GetShardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardInfoRequest.ProtoReflect.Descriptor instead.
func (*GetShardInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetShardInfoRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *GetShardInfoRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type ShardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	State         ShardInfo_ShardState   `protobuf:"varint,4,opt,name=state,proto3,enum=quidditch.data.ShardInfo_ShardState" json:"state,omitempty"`
	DocsCount     int64                  `protobuf:"varint,5,opt,name=docs_count,json=docsCount,proto3" json:"docs_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *ShardInfo) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *ShardInfo) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardInfo) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ShardInfo) GetState() ShardInfo_ShardState {
	if x != nil {
		return x.State
	}
	return ShardInfo_SHARD_STATE_UNKNOWN
}

func (x *ShardInfo) GetDocsCount() int64 {
	if x != nil {
		return x.DocsCount
	}
	return 0
}

func (x *ShardInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ShardInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShardInfo) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type RefreshShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshShardRequest) Reset() {
	*x = RefreshShardRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshShardRequest) ProtoMessage() {}

func (x *RefreshShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshShardRequest.ProtoReflect.Descriptor instead.
func (*RefreshShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshShardRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *RefreshShardRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type RefreshShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshShardResponse) Reset() {
	*x = RefreshShardResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshShardResponse) ProtoMessage() {}

func (x *RefreshShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshShardResponse.ProtoReflect.Descriptor instead.
func (*RefreshShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshShardResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type FlushShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushShardRequest) Reset() {
	*x = FlushShardRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushShardRequest) ProtoMessage() {}

func (x *FlushShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushShardRequest.ProtoReflect.Descriptor instead.
func (*FlushShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *FlushShardRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *FlushShardRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type FlushShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushShardResponse) Reset() {
	*x = FlushShardResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushShardResponse) ProtoMessage() {}

func (x *FlushShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushShardResponse.ProtoReflect.Descriptor instead.
func (*FlushShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *FlushShardResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type IndexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Document      *structpb.Struct       `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentRequest) Reset() {
	*x = IndexDocumentRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentRequest) ProtoMessage() {}

func (x *IndexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentRequest.ProtoReflect.Descriptor instead.
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *IndexDocumentRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *IndexDocumentRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *IndexDocumentRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IndexDocumentRequest) GetDocument() *structpb.Struct {
	if x != nil {
		return x.Document
	}
	return nil
}

type IndexDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentResponse) Reset() {
	*x = IndexDocumentResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentResponse) ProtoMessage() {}

func (x *IndexDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentResponse.ProtoReflect.Descriptor instead.
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *IndexDocumentResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *IndexDocumentResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IndexDocumentResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *GetDocumentRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *GetDocumentRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GetDocumentRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Document      *structpb.Struct       `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetDocumentResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *GetDocumentResponse) GetDocument() *structpb.Struct {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDocumentRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *DeleteDocumentRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *DeleteDocumentRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDocumentResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *DeleteDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BulkIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Items         []*BulkIndexItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkIndexRequest) Reset() {
	*x = BulkIndexRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIndexRequest) ProtoMessage() {}

func (x *BulkIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIndexRequest.ProtoReflect.Descriptor instead.
func (*BulkIndexRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *BulkIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *BulkIndexRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *BulkIndexRequest) GetItems() []*BulkIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BulkIndexItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Document      *structpb.Struct       `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkIndexItem) Reset() {
	*x = BulkIndexItem{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIndexItem) ProtoMessage() {}

func (x *BulkIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIndexItem.ProtoReflect.Descriptor instead.
func (*BulkIndexItem) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{17}
}

func (x *BulkIndexItem) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *BulkIndexItem) GetDocument() *structpb.Struct {
	if x != nil {
		return x.Document
	}
	return nil
}

type BulkIndexResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	HasErrors     bool                     `protobuf:"varint,1,opt,name=has_errors,json=hasErrors,proto3" json:"has_errors,omitempty"`
	Items         []*BulkIndexItemResponse `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TookMillis    int64                    `protobuf:"varint,3,opt,name=took_millis,json=tookMillis,proto3" json:"took_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkIndexResponse) Reset() {
	*x = BulkIndexResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIndexResponse) ProtoMessage() {}

func (x *BulkIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIndexResponse.ProtoReflect.Descriptor instead.
func (*BulkIndexResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{18}
}

func (x *BulkIndexResponse) GetHasErrors() bool {
	if x != nil {
		return x.HasErrors
	}
	return false
}

func (x *BulkIndexResponse) GetItems() []*BulkIndexItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BulkIndexResponse) GetTookMillis() int64 {
	if x != nil {
		return x.TookMillis
	}
	return 0
}

type BulkIndexItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkIndexItemResponse) Reset() {
	*x = BulkIndexItemResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkIndexItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIndexItemResponse) ProtoMessage() {}

func (x *BulkIndexItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIndexItemResponse.ProtoReflect.Descriptor instead.
func (*BulkIndexItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{19}
}

func (x *BulkIndexItemResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *BulkIndexItemResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *BulkIndexItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IndexName      string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId        int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Query          []byte                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // Serialized query DSL
	From           int32                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	Size           int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Sort           []string               `protobuf:"bytes,6,rep,name=sort,proto3" json:"sort,omitempty"`
	TrackTotalHits bool                   `protobuf:"varint,7,opt,name=track_total_hits,json=trackTotalHits,proto3" json:"track_total_hits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{20}
}

func (x *SearchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *SearchRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SearchRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SearchRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchRequest) GetTrackTotalHits() bool {
	if x != nil {
		return x.TrackTotalHits
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TookMillis    int64                  `protobuf:"varint,1,opt,name=took_millis,json=tookMillis,proto3" json:"took_millis,omitempty"`
	TimedOut      bool                   `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Shards        *ShardSearchStats      `protobuf:"bytes,3,opt,name=shards,proto3" json:"shards,omitempty"`
	Hits          *SearchHits            `protobuf:"bytes,4,opt,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{21}
}

func (x *SearchResponse) GetTookMillis() int64 {
	if x != nil {
		return x.TookMillis
	}
	return 0
}

func (x *SearchResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *SearchResponse) GetShards() *ShardSearchStats {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *SearchResponse) GetHits() *SearchHits {
	if x != nil {
		return x.Hits
	}
	return nil
}

type ShardSearchStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardSearchStats) Reset() {
	*x = ShardSearchStats{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSearchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSearchStats) ProtoMessage() {}

func (x *ShardSearchStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSearchStats.ProtoReflect.Descriptor instead.
func (*ShardSearchStats) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{22}
}

func (x *ShardSearchStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ShardSearchStats) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *ShardSearchStats) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type SearchHits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *TotalHits             `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	MaxScore      float64                `protobuf:"fixed64,2,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Hits          []*SearchHit           `protobuf:"bytes,3,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHits) Reset() {
	*x = SearchHits{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHits) ProtoMessage() {}

func (x *SearchHits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHits.ProtoReflect.Descriptor instead.
func (*SearchHits) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{23}
}

func (x *SearchHits) GetTotal() *TotalHits {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *SearchHits) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *SearchHits) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type TotalHits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"` // "eq" or "gte"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalHits) Reset() {
	*x = TotalHits{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalHits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalHits) ProtoMessage() {}

func (x *TotalHits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalHits.ProtoReflect.Descriptor instead.
func (*TotalHits) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{24}
}

func (x *TotalHits) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TotalHits) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Source        *structpb.Struct       `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Sort          []float64              `protobuf:"fixed64,4,rep,packed,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{25}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetSource() *structpb.Struct {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SearchHit) GetSort() []float64 {
	if x != nil {
		return x.Sort
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Query         []byte                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // Serialized query DSL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{26}
}

func (x *CountRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *CountRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CountRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{27}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetShardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardStatsRequest) Reset() {
	*x = GetShardStatsRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardStatsRequest) ProtoMessage() {}

func (x *GetShardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetShardStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{28}
}

func (x *GetShardStatsRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *GetShardStatsRequest) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type ShardStats struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IndexName               string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId                 int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	IsPrimary               bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	DocsCount               int64                  `protobuf:"varint,4,opt,name=docs_count,json=docsCount,proto3" json:"docs_count,omitempty"`
	DocsDeleted             int64                  `protobuf:"varint,5,opt,name=docs_deleted,json=docsDeleted,proto3" json:"docs_deleted,omitempty"`
	SizeBytes               int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SearchQueriesTotal      int64                  `protobuf:"varint,7,opt,name=search_queries_total,json=searchQueriesTotal,proto3" json:"search_queries_total,omitempty"`
	SearchQueriesTimeMillis int64                  `protobuf:"varint,8,opt,name=search_queries_time_millis,json=searchQueriesTimeMillis,proto3" json:"search_queries_time_millis,omitempty"`
	IndexingTotal           int64                  `protobuf:"varint,9,opt,name=indexing_total,json=indexingTotal,proto3" json:"indexing_total,omitempty"`
	IndexingTimeMillis      int64                  `protobuf:"varint,10,opt,name=indexing_time_millis,json=indexingTimeMillis,proto3" json:"indexing_time_millis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ShardStats) Reset() {
	*x = ShardStats{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStats) ProtoMessage() {}

func (x *ShardStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStats.ProtoReflect.Descriptor instead.
func (*ShardStats) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{29}
}

func (x *ShardStats) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *ShardStats) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardStats) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ShardStats) GetDocsCount() int64 {
	if x != nil {
		return x.DocsCount
	}
	return 0
}

func (x *ShardStats) GetDocsDeleted() int64 {
	if x != nil {
		return x.DocsDeleted
	}
	return 0
}

func (x *ShardStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ShardStats) GetSearchQueriesTotal() int64 {
	if x != nil {
		return x.SearchQueriesTotal
	}
	return 0
}

func (x *ShardStats) GetSearchQueriesTimeMillis() int64 {
	if x != nil {
		return x.SearchQueriesTimeMillis
	}
	return 0
}

func (x *ShardStats) GetIndexingTotal() int64 {
	if x != nil {
		return x.IndexingTotal
	}
	return 0
}

func (x *ShardStats) GetIndexingTimeMillis() int64 {
	if x != nil {
		return x.IndexingTimeMillis
	}
	return 0
}

type GetNodeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeShards bool                   `protobuf:"varint,1,opt,name=include_shards,json=includeShards,proto3" json:"include_shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatsRequest) Reset() {
	*x = GetNodeStatsRequest{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatsRequest) ProtoMessage() {}

func (x *GetNodeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{30}
}

func (x *GetNodeStatsRequest) GetIncludeShards() bool {
	if x != nil {
		return x.IncludeShards
	}
	return false
}

type DataNodeStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalShards        int32                  `protobuf:"varint,2,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	TotalDocs          int64                  `protobuf:"varint,3,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	TotalSizeBytes     int64                  `protobuf:"varint,4,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,6,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsagePercent   float64                `protobuf:"fixed64,7,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Shards             []*ShardStats          `protobuf:"bytes,9,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataNodeStats) Reset() {
	*x = DataNodeStats{}
	mi := &file_pkg_common_proto_data_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataNodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeStats) ProtoMessage() {}

func (x *DataNodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_data_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeStats.ProtoReflect.Descriptor instead.
func (*DataNodeStats) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_data_proto_rawDescGZIP(), []int{31}
}

func (x *DataNodeStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DataNodeStats) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *DataNodeStats) GetTotalDocs() int64 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *DataNodeStats) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *DataNodeStats) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *DataNodeStats) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *DataNodeStats) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *DataNodeStats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DataNodeStats) GetShards() []*ShardStats {
	if x != nil {
		return x.Shards
	}
	return nil
}

var File_pkg_common_proto_data_proto protoreflect.FileDescriptor

const file_pkg_common_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/common/proto/data.proto\x12\x0equidditch.data\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n" +
	"\x12CreateShardRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12L\n" +
	"\bsettings\x18\x04 \x03(\v20.quidditch.data.CreateShardRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x13CreateShardResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1b\n" +
	"\tshard_key\x18\x02 \x01(\tR\bshardKey\"N\n" +
	"\x12DeleteShardRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\"9\n" +
	"\x13DeleteShardResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"O\n" +
	"\x13GetShardInfoRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\"\xeb\x03\n" +
	"\tShardInfo\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12:\n" +
	"\x05state\x18\x04 \x01(\x0e2$.quidditch.data.ShardInfo.ShardStateR\x05state\x12\x1d\n" +
	"\n" +
	"docs_count\x18\x05 \x01(\x03R\tdocsCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x90\x01\n" +
	"\n" +
	"ShardState\x12\x17\n" +
	"\x13SHARD_STATE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18SHARD_STATE_INITIALIZING\x10\x01\x12\x17\n" +
	"\x13SHARD_STATE_STARTED\x10\x02\x12\x1a\n" +
	"\x16SHARD_STATE_RELOCATING\x10\x03\x12\x16\n" +
	"\x12SHARD_STATE_CLOSED\x10\x04\"O\n" +
	"\x13RefreshShardRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\":\n" +
	"\x14RefreshShardResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"M\n" +
	"\x11FlushShardRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\"8\n" +
	"\x12FlushShardResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x9c\x01\n" +
	"\x14IndexDocumentRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x123\n" +
	"\bdocument\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bdocument\"l\n" +
	"\x15IndexDocumentResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"e\n" +
	"\x12GetDocumentRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\"\x91\x01\n" +
	"\x13GetDocumentResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x123\n" +
	"\bdocument\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bdocument\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"h\n" +
	"\x15DeleteDocumentRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\"R\n" +
	"\x16DeleteDocumentResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x81\x01\n" +
	"\x10BulkIndexRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x123\n" +
	"\x05items\x18\x03 \x03(\v2\x1d.quidditch.data.BulkIndexItemR\x05items\"[\n" +
	"\rBulkIndexItem\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x123\n" +
	"\bdocument\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bdocument\"\x90\x01\n" +
	"\x11BulkIndexResponse\x12\x1d\n" +
	"\n" +
	"has_errors\x18\x01 \x01(\bR\thasErrors\x12;\n" +
	"\x05items\x18\x02 \x03(\v2%.quidditch.data.BulkIndexItemResponseR\x05items\x12\x1f\n" +
	"\vtook_millis\x18\x03 \x01(\x03R\n" +
	"tookMillis\"h\n" +
	"\x15BulkIndexItemResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc5\x01\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\fR\x05query\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x05R\x04from\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x12\n" +
	"\x04sort\x18\x06 \x03(\tR\x04sort\x12(\n" +
	"\x10track_total_hits\x18\a \x01(\bR\x0etrackTotalHits\"\xb8\x01\n" +
	"\x0eSearchResponse\x12\x1f\n" +
	"\vtook_millis\x18\x01 \x01(\x03R\n" +
	"tookMillis\x12\x1b\n" +
	"\ttimed_out\x18\x02 \x01(\bR\btimedOut\x128\n" +
	"\x06shards\x18\x03 \x01(\v2 .quidditch.data.ShardSearchStatsR\x06shards\x12.\n" +
	"\x04hits\x18\x04 \x01(\v2\x1a.quidditch.data.SearchHitsR\x04hits\"`\n" +
	"\x10ShardSearchStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\"\x89\x01\n" +
	"\n" +
	"SearchHits\x12/\n" +
	"\x05total\x18\x01 \x01(\v2\x19.quidditch.data.TotalHitsR\x05total\x12\x1b\n" +
	"\tmax_score\x18\x02 \x01(\x01R\bmaxScore\x12-\n" +
	"\x04hits\x18\x03 \x03(\v2\x19.quidditch.data.SearchHitR\x04hits\"=\n" +
	"\tTotalHits\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\"v\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12/\n" +
	"\x06source\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06source\x12\x12\n" +
	"\x04sort\x18\x04 \x03(\x01R\x04sort\"^\n" +
	"\fCountRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\fR\x05query\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"P\n" +
	"\x14GetShardStatsRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\"\x8e\x03\n" +
	"\n" +
	"ShardStats\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x1d\n" +
	"\n" +
	"docs_count\x18\x04 \x01(\x03R\tdocsCount\x12!\n" +
	"\fdocs_deleted\x18\x05 \x01(\x03R\vdocsDeleted\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x120\n" +
	"\x14search_queries_total\x18\a \x01(\x03R\x12searchQueriesTotal\x12;\n" +
	"\x1asearch_queries_time_millis\x18\b \x01(\x03R\x17searchQueriesTimeMillis\x12%\n" +
	"\x0eindexing_total\x18\t \x01(\x03R\rindexingTotal\x120\n" +
	"\x14indexing_time_millis\x18\n" +
	" \x01(\x03R\x12indexingTimeMillis\"<\n" +
	"\x13GetNodeStatsRequest\x12%\n" +
	"\x0einclude_shards\x18\x01 \x01(\bR\rincludeShards\"\xfb\x02\n" +
	"\rDataNodeStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\ftotal_shards\x18\x02 \x01(\x05R\vtotalShards\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x03 \x01(\x03R\ttotalDocs\x12(\n" +
	"\x10total_size_bytes\x18\x04 \x01(\x03R\x0etotalSizeBytes\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x06 \x01(\x01R\x12memoryUsagePercent\x12,\n" +
	"\x12disk_usage_percent\x18\a \x01(\x01R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x122\n" +
	"\x06shards\x18\t \x03(\v2\x1a.quidditch.data.ShardStatsR\x06shards2\xdc\b\n" +
	"\vDataService\x12V\n" +
	"\vCreateShard\x12\".quidditch.data.CreateShardRequest\x1a#.quidditch.data.CreateShardResponse\x12V\n" +
	"\vDeleteShard\x12\".quidditch.data.DeleteShardRequest\x1a#.quidditch.data.DeleteShardResponse\x12N\n" +
	"\fGetShardInfo\x12#.quidditch.data.GetShardInfoRequest\x1a\x19.quidditch.data.ShardInfo\x12Y\n" +
	"\fRefreshShard\x12#.quidditch.data.RefreshShardRequest\x1a$.quidditch.data.RefreshShardResponse\x12S\n" +
	"\n" +
	"FlushShard\x12!.quidditch.data.FlushShardRequest\x1a\".quidditch.data.FlushShardResponse\x12\\\n" +
	"\rIndexDocument\x12$.quidditch.data.IndexDocumentRequest\x1a%.quidditch.data.IndexDocumentResponse\x12V\n" +
	"\vGetDocument\x12\".quidditch.data.GetDocumentRequest\x1a#.quidditch.data.GetDocumentResponse\x12_\n" +
	"\x0eDeleteDocument\x12%.quidditch.data.DeleteDocumentRequest\x1a&.quidditch.data.DeleteDocumentResponse\x12P\n" +
	"\tBulkIndex\x12 .quidditch.data.BulkIndexRequest\x1a!.quidditch.data.BulkIndexResponse\x12G\n" +
	"\x06Search\x12\x1d.quidditch.data.SearchRequest\x1a\x1e.quidditch.data.SearchResponse\x12D\n" +
	"\x05Count\x12\x1c.quidditch.data.CountRequest\x1a\x1d.quidditch.data.CountResponse\x12Q\n" +
	"\rGetShardStats\x12$.quidditch.data.GetShardStatsRequest\x1a\x1a.quidditch.data.ShardStats\x12R\n" +
	"\fGetNodeStats\x12#.quidditch.data.GetNodeStatsRequest\x1a\x1d.quidditch.data.DataNodeStatsB1Z/github.com/quidditch/quidditch/pkg/common/protob\x06proto3"

var (
	file_pkg_common_proto_data_proto_rawDescOnce sync.Once
	file_pkg_common_proto_data_proto_rawDescData []byte
)

func file_pkg_common_proto_data_proto_rawDescGZIP() []byte {
	file_pkg_common_proto_data_proto_rawDescOnce.Do(func() {
		file_pkg_common_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_common_proto_data_proto_rawDesc), len(file_pkg_common_proto_data_proto_rawDesc)))
	})
	return file_pkg_common_proto_data_proto_rawDescData
}

var file_pkg_common_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_common_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pkg_common_proto_data_proto_goTypes = []any{
	(ShardInfo_ShardState)(0),      // 0: quidditch.data.ShardInfo.ShardState
	(*CreateShardRequest)(nil),     // 1: quidditch.data.CreateShardRequest
	(*CreateShardResponse)(nil),    // 2: quidditch.data.CreateShardResponse
	(*DeleteShardRequest)(nil),     // 3: quidditch.data.DeleteShardRequest
	(*DeleteShardResponse)(nil),    // 4: quidditch.data.DeleteShardResponse
	(*GetShardInfoRequest)(nil),    // 5: quidditch.data.GetShardInfoRequest
	(*ShardInfo)(nil),              // 6: quidditch.data.ShardInfo
	(*RefreshShardRequest)(nil),    // 7: quidditch.data.RefreshShardRequest
	(*RefreshShardResponse)(nil),   // 8: quidditch.data.RefreshShardResponse
	(*FlushShardRequest)(nil),      // 9: quidditch.data.FlushShardRequest
	(*FlushShardResponse)(nil),     // 10: quidditch.data.FlushShardResponse
	(*IndexDocumentRequest)(nil),   // 11: quidditch.data.IndexDocumentRequest
	(*IndexDocumentResponse)(nil),  // 12: quidditch.data.IndexDocumentResponse
	(*GetDocumentRequest)(nil),     // 13: quidditch.data.GetDocumentRequest
	(*GetDocumentResponse)(nil),    // 14: quidditch.data.GetDocumentResponse
	(*DeleteDocumentRequest)(nil),  // 15: quidditch.data.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 16: quidditch.data.DeleteDocumentResponse
	(*BulkIndexRequest)(nil),       // 17: quidditch.data.BulkIndexRequest
	(*BulkIndexItem)(nil),          // 18: quidditch.data.BulkIndexItem
	(*BulkIndexResponse)(nil),      // 19: quidditch.data.BulkIndexResponse
	(*BulkIndexItemResponse)(nil),  // 20: quidditch.data.BulkIndexItemResponse
	(*SearchRequest)(nil),          // 21: quidditch.data.SearchRequest
	(*SearchResponse)(nil),         // 22: quidditch.data.SearchResponse
	(*ShardSearchStats)(nil),       // 23: quidditch.data.ShardSearchStats
	(*SearchHits)(nil),             // 24: quidditch.data.SearchHits
	(*TotalHits)(nil),              // 25: quidditch.data.TotalHits
	(*SearchHit)(nil),              // 26: quidditch.data.SearchHit
	(*CountRequest)(nil),           // 27: quidditch.data.CountRequest
	(*CountResponse)(nil),          // 28: quidditch.data.CountResponse
	(*GetShardStatsRequest)(nil),   // 29: quidditch.data.GetShardStatsRequest
	(*ShardStats)(nil),             // 30: quidditch.data.ShardStats
	(*GetNodeStatsRequest)(nil),    // 31: quidditch.data.GetNodeStatsRequest
	(*DataNodeStats)(nil),          // 32: quidditch.data.DataNodeStats
	nil,                            // 33: quidditch.data.CreateShardRequest.SettingsEntry
	(*timestamppb.Timestamp)(nil),  // 34: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 35: google.protobuf.Struct
}
var file_pkg_common_proto_data_proto_depIdxs = []int32{
	33, // 0: quidditch.data.CreateShardRequest.settings:type_name -> quidditch.data.CreateShardRequest.SettingsEntry
	0,  // 1: quidditch.data.ShardInfo.state:type_name -> quidditch.data.ShardInfo.ShardState
	34, // 2: quidditch.data.ShardInfo.created_at:type_name -> google.protobuf.Timestamp
	34, // 3: quidditch.data.ShardInfo.last_updated:type_name -> google.protobuf.Timestamp
	35, // 4: quidditch.data.IndexDocumentRequest.document:type_name -> google.protobuf.Struct
	35, // 5: quidditch.data.GetDocumentResponse.document:type_name -> google.protobuf.Struct
	18, // 6: quidditch.data.BulkIndexRequest.items:type_name -> quidditch.data.BulkIndexItem
	35, // 7: quidditch.data.BulkIndexItem.document:type_name -> google.protobuf.Struct
	20, // 8: quidditch.data.BulkIndexResponse.items:type_name -> quidditch.data.BulkIndexItemResponse
	23, // 9: quidditch.data.SearchResponse.shards:type_name -> quidditch.data.ShardSearchStats
	24, // 10: quidditch.data.SearchResponse.hits:type_name -> quidditch.data.SearchHits
	25, // 11: quidditch.data.SearchHits.total:type_name -> quidditch.data.TotalHits
	26, // 12: quidditch.data.SearchHits.hits:type_name -> quidditch.data.SearchHit
	35, // 13: quidditch.data.SearchHit.source:type_name -> google.protobuf.Struct
	30, // 14: quidditch.data.DataNodeStats.shards:type_name -> quidditch.data.ShardStats
	1,  // 15: quidditch.data.DataService.CreateShard:input_type -> quidditch.data.CreateShardRequest
	3,  // 16: quidditch.data.DataService.DeleteShard:input_type -> quidditch.data.DeleteShardRequest
	5,  // 17: quidditch.data.DataService.GetShardInfo:input_type -> quidditch.data.GetShardInfoRequest
	7,  // 18: quidditch.data.DataService.RefreshShard:input_type -> quidditch.data.RefreshShardRequest
	9,  // 19: quidditch.data.DataService.FlushShard:input_type -> quidditch.data.FlushShardRequest
	11, // 20: quidditch.data.DataService.IndexDocument:input_type -> quidditch.data.IndexDocumentRequest
	13, // 21: quidditch.data.DataService.GetDocument:input_type -> quidditch.data.GetDocumentRequest
	15, // 22: quidditch.data.DataService.DeleteDocument:input_type -> quidditch.data.DeleteDocumentRequest
	17, // 23: quidditch.data.DataService.BulkIndex:input_type -> quidditch.data.BulkIndexRequest
	21, // 24: quidditch.data.DataService.Search:input_type -> quidditch.data.SearchRequest
	27, // 25: quidditch.data.DataService.Count:input_type -> quidditch.data.CountRequest
	29, // 26: quidditch.data.DataService.GetShardStats:input_type -> quidditch.data.GetShardStatsRequest
	31, // 27: quidditch.data.DataService.GetNodeStats:input_type -> quidditch.data.GetNodeStatsRequest
	2,  // 28: quidditch.data.DataService.CreateShard:output_type -> quidditch.data.CreateShardResponse
	4,  // 29: quidditch.data.DataService.DeleteShard:output_type -> quidditch.data.DeleteShardResponse
	6,  // 30: quidditch.data.DataService.GetShardInfo:output_type -> quidditch.data.ShardInfo
	8,  // 31: quidditch.data.DataService.RefreshShard:output_type -> quidditch.data.RefreshShardResponse
	10, // 32: quidditch.data.DataService.FlushShard:output_type -> quidditch.data.FlushShardResponse
	12, // 33: quidditch.data.DataService.IndexDocument:output_type -> quidditch.data.IndexDocumentResponse
	14, // 34: quidditch.data.DataService.GetDocument:output_type -> quidditch.data.GetDocumentResponse
	16, // 35: quidditch.data.DataService.DeleteDocument:output_type -> quidditch.data.DeleteDocumentResponse
	19, // 36: quidditch.data.DataService.BulkIndex:output_type -> quidditch.data.BulkIndexResponse
	22, // 37: quidditch.data.DataService.Search:output_type -> quidditch.data.SearchResponse
	28, // 38: quidditch.data.DataService.Count:output_type -> quidditch.data.CountResponse
	30, // 39: quidditch.data.DataService.GetShardStats:output_type -> quidditch.data.ShardStats
	32, // 40: quidditch.data.DataService.GetNodeStats:output_type -> quidditch.data.DataNodeStats
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_common_proto_data_proto_init() }
func file_pkg_common_proto_data_proto_init() {
	if File_pkg_common_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_common_proto_data_proto_rawDesc), len(file_pkg_common_proto_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_common_proto_data_proto_goTypes,
		DependencyIndexes: file_pkg_common_proto_data_proto_depIdxs,
		EnumInfos:         file_pkg_common_proto_data_proto_enumTypes,
		MessageInfos:      file_pkg_common_proto_data_proto_msgTypes,
	}.Build()
	File_pkg_common_proto_data_proto = out.File
	file_pkg_common_proto_data_proto_goTypes = nil
	file_pkg_common_proto_data_proto_depIdxs = nil
}
