package bulk

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseBulkRequest_Index(t *testing.T) {
	body := []byte(`{"index":{"_index":"test","_id":"1"}}
{"field1":"value1","field2":"value2"}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	require.NotNil(t, req)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationIndex, op.Type)
	assert.Equal(t, "test", op.Index)
	assert.Equal(t, "1", op.ID)
	assert.NotNil(t, op.Document)
	assert.Equal(t, "value1", op.Document["field1"])
	assert.Equal(t, "value2", op.Document["field2"])
}

func TestParseBulkRequest_Create(t *testing.T) {
	body := []byte(`{"create":{"_index":"test","_id":"2"}}
{"title":"Test Document"}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationCreate, op.Type)
	assert.Equal(t, "test", op.Index)
	assert.Equal(t, "2", op.ID)
	assert.Equal(t, "Test Document", op.Document["title"])
}

func TestParseBulkRequest_Update(t *testing.T) {
	body := []byte(`{"update":{"_index":"test","_id":"3"}}
{"doc":{"field":"updated_value"}}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationUpdate, op.Type)
	assert.Equal(t, "test", op.Index)
	assert.Equal(t, "3", op.ID)
	assert.NotNil(t, op.UpdateDoc)
	assert.Equal(t, "updated_value", op.UpdateDoc["field"])
}

func TestParseBulkRequest_Delete(t *testing.T) {
	body := []byte(`{"delete":{"_index":"test","_id":"4"}}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationDelete, op.Type)
	assert.Equal(t, "test", op.Index)
	assert.Equal(t, "4", op.ID)
	assert.Nil(t, op.Document)
}

func TestParseBulkRequest_Mixed(t *testing.T) {
	body := []byte(`{"index":{"_index":"test","_id":"1"}}
{"field":"value1"}
{"create":{"_index":"test","_id":"2"}}
{"field":"value2"}
{"update":{"_index":"test","_id":"3"}}
{"doc":{"field":"value3"}}
{"delete":{"_index":"test","_id":"4"}}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 4, len(req.Operations))

	// Check index operation
	assert.Equal(t, OperationIndex, req.Operations[0].Type)
	assert.Equal(t, "1", req.Operations[0].ID)

	// Check create operation
	assert.Equal(t, OperationCreate, req.Operations[1].Type)
	assert.Equal(t, "2", req.Operations[1].ID)

	// Check update operation
	assert.Equal(t, OperationUpdate, req.Operations[2].Type)
	assert.Equal(t, "3", req.Operations[2].ID)

	// Check delete operation
	assert.Equal(t, OperationDelete, req.Operations[3].Type)
	assert.Equal(t, "4", req.Operations[3].ID)
}

func TestParseBulkRequest_AutoGeneratedID(t *testing.T) {
	body := []byte(`{"index":{"_index":"test"}}
{"field":"value"}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationIndex, op.Type)
	assert.Equal(t, "test", op.Index)
	assert.Equal(t, "", op.ID) // ID is empty, should be auto-generated
}

func TestParseBulkRequest_EmptyBody(t *testing.T) {
	body := []byte("")

	_, err := ParseBulkRequest(body)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "empty bulk request")
}

func TestParseBulkRequest_MissingDocument(t *testing.T) {
	body := []byte(`{"index":{"_index":"test","_id":"1"}}
`)

	_, err := ParseBulkRequest(body)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "missing document body")
}

func TestParseBulkRequest_MissingIndex(t *testing.T) {
	body := []byte(`{"index":{"_id":"1"}}
{"field":"value"}
`)

	_, err := ParseBulkRequest(body)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "missing _index")
}

func TestParseBulkRequest_InvalidJSON(t *testing.T) {
	body := []byte(`{"index":{"_index":"test","_id":"1"}}
{invalid json}
`)

	_, err := ParseBulkRequest(body)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "failed to parse document")
}

func TestParseBulkRequest_UnknownOperation(t *testing.T) {
	body := []byte(`{"unknown":{"_index":"test","_id":"1"}}
{"field":"value"}
`)

	_, err := ParseBulkRequest(body)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "unknown bulk operation")
}

func TestParseBulkRequest_WithEmptyLines(t *testing.T) {
	body := []byte(`{"index":{"_index":"test","_id":"1"}}
{"field":"value1"}

{"index":{"_index":"test","_id":"2"}}
{"field":"value2"}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 2, len(req.Operations))
}

func TestBulkResponse_AddItem(t *testing.T) {
	resp := NewBulkResponse()
	assert.False(t, resp.Errors)
	assert.Equal(t, 0, len(resp.Items))

	// Add successful item
	resp.AddItem(OperationIndex, &BulkItemResult{
		Index:  "test",
		ID:     "1",
		Status: 201,
		Result: "created",
	})

	assert.False(t, resp.Errors)
	assert.Equal(t, 1, len(resp.Items))

	// Add failed item
	resp.AddItem(OperationIndex, &BulkItemResult{
		Index:  "test",
		ID:     "2",
		Status: 500,
		Error: &BulkItemError{
			Type:   "index_failed_exception",
			Reason: "test error",
		},
	})

	assert.True(t, resp.Errors)
	assert.Equal(t, 2, len(resp.Items))
}

func TestBulkResponse_Structure(t *testing.T) {
	resp := NewBulkResponse()
	resp.Took = 100

	resp.AddItem(OperationIndex, &BulkItemResult{
		Index:   "test",
		ID:      "1",
		Version: 1,
		Result:  "created",
		Status:  201,
		Shards: &BulkItemShards{
			Total:      1,
			Successful: 1,
			Failed:     0,
		},
	})

	resp.AddItem(OperationDelete, &BulkItemResult{
		Index:   "test",
		ID:      "2",
		Version: 2,
		Result:  "deleted",
		Status:  200,
		Shards: &BulkItemShards{
			Total:      1,
			Successful: 1,
			Failed:     0,
		},
	})

	assert.Equal(t, int64(100), resp.Took)
	assert.False(t, resp.Errors)
	assert.Equal(t, 2, len(resp.Items))

	// Verify structure
	assert.Contains(t, resp.Items[0], "index")
	assert.Contains(t, resp.Items[1], "delete")

	indexResult := resp.Items[0]["index"]
	assert.Equal(t, "test", indexResult.Index)
	assert.Equal(t, "1", indexResult.ID)
	assert.Equal(t, int64(1), indexResult.Version)
	assert.Equal(t, "created", indexResult.Result)
	assert.Equal(t, 201, indexResult.Status)

	deleteResult := resp.Items[1]["delete"]
	assert.Equal(t, "test", deleteResult.Index)
	assert.Equal(t, "2", deleteResult.ID)
	assert.Equal(t, int64(2), deleteResult.Version)
	assert.Equal(t, "deleted", deleteResult.Result)
	assert.Equal(t, 200, deleteResult.Status)
}

func TestParseBulkRequest_UpdateWithoutDoc(t *testing.T) {
	body := []byte(`{"update":{"_index":"test","_id":"1"}}
{"field":"value"}
`)

	req, err := ParseBulkRequest(body)
	require.NoError(t, err)
	assert.Equal(t, 1, len(req.Operations))

	op := req.Operations[0]
	assert.Equal(t, OperationUpdate, op.Type)
	assert.NotNil(t, op.UpdateDoc)
	assert.Equal(t, "value", op.UpdateDoc["field"])
}
